[workspace]
resolver = "2"
members = [
    "dim/",
    "dim-core",
    "dim-auth",
    "dim-database",
    "dim-events",
    "dim-extern-api",
    "dim-web",
    "dim-utils",
]
exclude = ["vendor/nightfall"]

[workspace.package]
version = "0.3.0"
authors = ["Valerian G. <valerian@dusklabs.io>"]
edition = "2021"
license = "AGPL-3.0-only"

[profile.dev]
codegen-units = 16

[patch."https://github.com/Dusk-Labs/nightfall"]
nightfall = { path = "vendor/nightfall" }
