version: "3.8"
services:
  eclipse:
    container_name: eclipse
    image: ghcr.io/madebyjordan/eclipse:dev
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - /<host_config_folder>:/opt/eclipse/config
      - /<host_metadata_folder>:/opt/eclipse/metadata
      - /<host_cache_folder>:/opt/eclipse/streaming_cache
      - /<host_logs_folder>:/opt/eclipse/logs
      - /<host_media_path>:/media
      # Add more folders like so:
      # - /<host_media_path>:/media2
    # Use the below lines to pass your device with hardware acceleration
    devices:
      - /<device>:/<device>
      # VAAPI Device example:
      # - /dev/dri/renderD128:/dev/dri/renderD128
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 30s
