name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_DIR: ${{ github.workspace }}/target

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y libva-dev libva-drm2 libva2 sqlite3 ffmpeg
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.93.1
        with:
          components: rustfmt, clippy

      - uses: actions/setup-node@v7
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack
        run: corepack enable

      - name: Verify source installation
        run: ./scripts/bootstrap.sh --release

      - name: Download ffmpeg artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "Dusk-Labs/ffmpeg-static"
          version: "tags/ffmpeg-all-0.0.1"
          file: "ffmpeg"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download ffprobe artifact
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "Dusk-Labs/ffmpeg-static"
          version: "tags/ffmpeg-all-0.0.1"
          file: "ffprobe"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release dir
        run: |
          mkdir -p release/utils
          cp ffmpeg release/utils/ffmpeg
          cp ffprobe release/utils/ffprobe
          chmod +x release/utils/ffmpeg
          chmod +x release/utils/ffprobe

      - name: Create Cargo target directory
        run: mkdir -p target

      - name: Test Dim
        run: cargo test --workspace --tests --locked

      - name: Copy dim binaries
        run: |
          cp target/release/dim release/dim
          chmod +x release/dim

      - name: Compress release dir
        run: tar -zcvf release.tar.gz release

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.tar.gz
